name: Build Eleventy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm run build -- --pathprefix=wrongos

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./output
          github_token: ${{ secrets.GITHUB_TOKEN }}